'use client'
import type { JobFactors } from '@/lib/types'
import { DEFAULT_TRUCK_HOLD, type MoveDatePlan } from '@/lib/estimate-services'
export function MoveTimingPanel({ factors, moveDate, onChange }: { factors: JobFactors; moveDate?: string; onChange: (factors: JobFactors) => void }) {
  const d = factors.moveDatePlan || { mode: 'confirmed', firstDate: moveDate }
  const h = { ...DEFAULT_TRUCK_HOLD, ...factors.truckHold }
  return <section className="space-y-3 rounded-xl border border-[var(--app-line)] bg-white p-4" aria-label="Date choices and overnight hold">
    <h3 className="font-semibold">Dates and overnight plans</h3>
    <label className="block text-xs">How settled are the dates?<select aria-label="Date certainty" className="crm-input mt-1 w-full" value={d.mode} onChange={e => onChange({ ...factors, moveDatePlan: { ...d, mode: e.target.value as MoveDatePlan['mode'] } })}><option value="confirmed">Date confirmed</option><option value="alternatives">Choosing between two dates</option><option value="range">Within a date range</option><option value="unknown">Date still unknown</option></select></label>
    {d.mode === 'confirmed' && <label className="block text-xs">Confirmed pickup date<input type="date" className="crm-input mt-1 w-full" value={d.firstDate || moveDate || ''} onChange={e => onChange({ ...factors, moveDatePlan: { ...d, firstDate: e.target.value } })}/></label>}
    {d.mode !== 'confirmed' && <div className="grid gap-3 sm:grid-cols-2">{d.mode !== 'unknown' && <>{(['firstDate', 'secondDate'] as const).map((key, i) => <label key={key} className="text-xs">{d.mode === 'range' ? (i ? 'Latest date' : 'Earliest date') : `Possible date ${i + 1}`}<input type="date" aria-label={`Possible date ${i + 1}`} className="crm-input mt-1 w-full" value={d[key] || ''} onChange={e => onChange({ ...factors, moveDatePlan: { ...d, [key]: e.target.value } })}/></label>)}</>}<label className="text-xs">Call to confirm on<input type="date" className="crm-input mt-1 w-full" value={d.followUpDate || ''} onChange={e => onChange({ ...factors, moveDatePlan: { ...d, followUpDate: e.target.value } })}/></label><label className="text-xs">What are we waiting for?<input className="crm-input mt-1 w-full" value={d.note || ''} onChange={e => onChange({ ...factors, moveDatePlan: { ...d, note: e.target.value } })} placeholder="Closing confirmation from lawyer"/></label></div>}
    <label className="block text-xs">Keep the load in the truck overnight?<select aria-label="Overnight truck hold" className="crm-input mt-1 w-full" value={h.status} onChange={e => onChange({ ...factors, truckHold: { ...h, status: e.target.value as typeof h.status } })}><option value="none">No</option><option value="possible">Possibly — confirm on follow-up</option><option value="confirmed">Yes — include in estimate</option></select></label>
    {h.status !== 'none' && <p className="text-xs text-[var(--app-muted)]">A loaded truck hold is separate from warehouse storage. {h.status === 'possible' ? 'It is not included in the price until confirmed. Saving schedules a confirmation follow-up.' : 'Enter actual operating costs, then apply it with the service package.'}</p>}
    {h.status === 'confirmed' && <div className="grid gap-3 sm:grid-cols-3">{([['nights','Nights'],['trucks','Trucks'],['truckCostPerNight','Truck cost / night'],['secureParkingCostPerNight','Secure parking / truck / night'],['extraDeliveryCost','Additional delivery / crew cost']] as const).map(([key,label]) => <label key={key} className="text-xs">{label}<input type="number" min={key === 'nights' || key === 'trucks' ? 1 : 0} className="crm-input mt-1 w-full" value={h[key]} onChange={e => onChange({ ...factors, truckHold: { ...h, [key]: Number(e.target.value) } })}/></label>)}<label className="text-xs">Delivery date<input type="date" className="crm-input mt-1 w-full" value={h.deliveryDate || ''} onChange={e => onChange({ ...factors, truckHold: { ...h, deliveryDate: e.target.value } })}/></label><label className="text-xs sm:col-span-3">Confirmed secure holding location<input className="crm-input mt-1 w-full" value={h.location || ''} onChange={e => onChange({ ...factors, truckHold: { ...h, location: e.target.value } })}/></label></div>}
  </section>
}
