const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),crypto=require('node:crypto');
function compile(file,stubs={},globals={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,{exports,Request,Response,URL,console,Buffer,AbortSignal,require:n=>stubs[n]||require(n),...globals});return exports}
const topic='arn:aws:sns:us-east-2:322694470585:saturn-crm-inbound-email';
test('SNS signature rejects wrong topic/cert and validates a signed envelope',async()=>{const {privateKey,publicKey}=crypto.generateKeyPairSync('rsa',{modulusLength:2048});const e={Type:'Notification',Message:'{}',MessageId:'id',Timestamp:new Date().toISOString(),TopicArn:topic,SignatureVersion:'2',SigningCertURL:'https://sns.us-east-2.amazonaws.com/SimpleNotificationService-test.pem'};e.Signature=crypto.sign('RSA-SHA256',Buffer.from(['Message','MessageId','Timestamp','TopicArn','Type'].map(k=>k+'\n'+e[k]+'\n').join('')),privateKey).toString('base64');const a=compile('lib/server/ses-inbound-signature.ts',{}, {fetch:async()=>new Response(publicKey.export({type:'spki',format:'pem'}))});assert.equal(await a.verifySesInboundSns(e,topic),true);assert.equal(await a.verifySesInboundSns({...e,Message:'changed'},topic),false);assert.equal(await a.verifySesInboundSns({...e,SigningCertURL:'https://evil.example/cert.pem'},topic),false);assert.equal(await a.verifySesInboundSns(e,topic+'-other'),false)});
function fixture({signature=true,failedImport=false,scan='PASS',bucket='test-bucket'}={}){const imports=[];let reads=0;class S3Client{async send(){reads++;return {ContentLength:200,Body:{transformToByteArray:async()=>Buffer.from('From: Customer <customer@example.com>\r\nTo: business@inbound.starmovers.ca\r\nSubject: Re: Quote\r\nContent-Type: text/plain; charset=utf-8\r\n\r\nPlease confirm the date.')}}}};const a=compile('app/api/sales/inbox/ses-inbound/route.ts',{'@aws-sdk/client-s3':{S3Client,GetObjectCommand:class{constructor(x){this.input=x}}},'@aws-sdk/client-sns':{},'@/lib/server/runtime':{readEnv:k=>({SES_INBOUND_TOPIC_ARN:topic,SES_INBOUND_BUCKET:'test-bucket'})[k]||'',getWorkerSharedSecret:()=> 'test-secret'},'@/lib/server/ses-inbound-signature':{verifySesInboundSns:async()=>signature},'../email-inbound/route':{POST:async req=>{imports.push({headers:req.headers,body:await req.json()});return Response.json({ok:!failedImport},{status:failedImport?500:200})}}});const message={notificationType:'Received',mail:{messageId:'message-id',timestamp:new Date().toISOString()},receipt:{recipients:['business@inbound.starmovers.ca'],spamVerdict:{status:scan},virusVerdict:{status:'PASS'},action:{type:'S3',bucketName:bucket,objectKey:'incoming/message-id'}}};return {imports,reads:()=>reads,post:()=>a.POST(new Request('https://test.invalid',{method:'POST',body:JSON.stringify({Type:'Notification',Message:JSON.stringify(message)})}))}}
test('verified S3 email imports decoded MIME and stable provider ID',async()=>{const f=fixture();assert.equal((await f.post()).status,200);assert.equal(f.imports[0].body.body.trim(),'Please confirm the date.');assert.equal(f.imports[0].body.providerMessageId,'message-id');assert.equal(f.imports[0].headers.get('x-internal-secret'),'test-secret')});
test('forged signature and foreign S3 bucket never read or import',async()=>{for(const opt of [{signature:false},{bucket:'foreign-bucket'}]){const f=fixture(opt);assert.ok((await f.post()).status>=400);assert.equal(f.reads(),0);assert.equal(f.imports.length,0)}});
test('failed content scan retains email without importing',async()=>{const f=fixture({scan:'FAIL'});const r=await f.post();assert.equal((await r.json()).quarantined,true);assert.equal(f.reads(),0)});
test('import failures return retryable status',async()=>{assert.equal((await fixture({failedImport:true}).post()).status,503)});
function importFixture(){const saved=[];let automations=0;const db=new Set();const a=compile('app/api/sales/inbox/email-inbound/route.ts',{'next/server':{NextResponse:{json:(v,i)=>Response.json(v,i)}},'@/lib/sales':{uid:()=> 'fixture-id'},'@/lib/server/runtime':{getWorkerSharedSecret:()=> 'secret',requireSupabaseEnv:()=>({url:'https://db.invalid',headers:{}})},'@/lib/server/partnership-inbound':{pausePartnershipSequenceForInbound:async()=>({matched:false})},'@/lib/server/lead-intelligence-refresh':{queueLeadIntelligenceRefresh:()=>{}},'@/lib/server/sales-automation':{processInboundAutomationEvent:async()=>{automations++;return {lead:null}}},'@/lib/server/internal-notifications':{sendRepAlertEmail:async()=>{}},'@/lib/server/sales-repository':{saveSalesEmail:async x=>{saved.push(x);db.add(x.id)},saveFollowUpLog:async()=>{}}},{fetch:async url=>Response.json(db.has(new URL(url).searchParams.get('id').slice(3))?[{id:'existing'}]:[])});return {saved,automations:()=>automations,post:(auth=true)=>a.POST(new Request('https://test.invalid',{method:'POST',headers:auth?{'x-internal-secret':'secret'}:{},body:JSON.stringify({from:'customer@example.com',to:'business@inbound.starmovers.ca',subject:'Reply',body:'Hello',providerMessageId:'stable-id'})}))}}
test('internal email imports fail closed without authentication',async()=>{const f=importFixture();assert.equal((await f.post(false)).status,401);assert.equal(f.saved.length,0)});
test('provider replay does not duplicate email or automation',async()=>{const f=importFixture();assert.equal((await f.post()).status,200);assert.equal((await (await f.post()).json()).duplicate,true);assert.equal(f.saved.length,1);assert.equal(f.automations(),1)});
