'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'

export default function Partner360Dashboard({ endpoint, backHref }: { endpoint: string; backHref?: string }) {
  const [data, setData] = useState<any>(null); const [error, setError] = useState(''); const [tab, setTab] = useState('overview')
  async function load() { const response = await fetch(endpoint, { cache: 'no-store' }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body) }
  useEffect(() => { load().catch(e => setError(e.message)) }, [endpoint])
  async function add(resource: string, input: any) { const response = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ resource, input }) }); const body = await response.json(); if (!response.ok) return setError(body.error); await load() }
  if (error) return <main className="crm-shell"><div className="rounded-xl bg-rose-50 p-4 text-rose-700">{error}</div></main>
  if (!data) return <main className="crm-shell text-sm text-slate-500">Loading Partner 360…</main>
  const p = data.partner; const openClaims = data.claims.filter((x:any) => x.status !== 'closed'); const openActions = data.correctiveActions.filter((x:any) => x.status !== 'resolved')
  const tabs = ['overview','jobs','team','vehicles','compliance','claims','earnings','performance','audit']
  return <main className="crm-shell space-y-5"><header className="flex flex-wrap justify-between gap-3"><div>{backHref && <Link href={backHref} className="text-xs font-bold text-slate-500">← Partner network</Link>}<p className="mt-2 text-xs font-bold uppercase tracking-[.18em] text-[#C99700]">Partner 360</p><h1 className="font-display text-2xl font-bold text-[#071421]">{p.company_name}</h1><p className="text-sm text-slate-500">{p.partner_code || 'Partner ID pending'} · {p.lifecycle_status} · {data.performance.tier}</p></div><div className="rounded-2xl bg-[#071421] px-6 py-4 text-white"><p className="text-xs uppercase opacity-60">Partner score</p><p className="text-3xl font-black">{data.performance.score}<span className="text-base opacity-60">/100</span></p></div></header>
    <nav className="flex gap-2 overflow-x-auto pb-1">{tabs.map(item => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold capitalize ${tab === item ? 'bg-[#071421] text-white' : 'border bg-white'}`}>{item}</button>)}</nav>
    {tab === 'overview' && <div className="grid gap-4 md:grid-cols-4">{[['Upcoming jobs',data.assignments.filter((x:any)=>!['completed','cancelled'].includes(x.status)).length],['Open claims',openClaims.length],['Compliance alerts',data.compliance.filter((x:any)=>x.state!=='compliant').length],['Pending earnings',data.balances ? `$${Number(data.balances.pending).toFixed(2)}` : 'Restricted']].map(([label,value])=><div key={String(label)} className="rounded-2xl border bg-white p-5"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>)}</div>}
    {tab === 'jobs' && <Table rows={data.assignments} columns={['lead_id','role','status','expected_start','version','acknowledged_version']} empty="No partner assignments yet."/>}
    {tab === 'team' && <><div className="flex flex-wrap gap-2"><QuickAdd label="Add crew member" fields={['name','email','phone','role']} defaults={{role:'mover',status:'active'}} onAdd={input=>add('member',input)}/>{backHref && <QuickAdd label="Provision portal login" fields={['name','email','password','role']} defaults={{role:'partner_admin'}} onAdd={input=>add('portal_user',input)}/>}</div><Table rows={data.members} columns={['name','role','status','phone','approved_for_jobs']}/></>}
    {tab === 'vehicles' && <><QuickAdd label="Add vehicle" fields={['unit_code','vehicle_type','size_label']} defaults={{status:'active',ownership:'partner_owned'}} onAdd={input=>add('vehicle',input)}/><Table rows={data.vehicles} columns={['unit_code','vehicle_type','size_label','status','insurance_verified','brand_compliant']}/></>}
    {tab === 'compliance' && <div className="grid gap-3 md:grid-cols-2">{data.compliance.map((x:any)=><div key={x.id} className={`rounded-xl border p-4 ${x.state==='expired'||x.state==='missing'?'border-rose-200 bg-rose-50':'bg-white'}`}><div className="flex justify-between"><b>{x.label}</b><span className="text-xs font-bold uppercase">{x.state}</span></div><p className="mt-1 text-xs text-slate-500">{x.document?.expires_at ? `Expires ${x.document.expires_at}` : x.conditional_note || 'No expiry recorded'}</p></div>)}</div>}
    {tab === 'claims' && <><QuickAdd label="Open claim" fields={['lead_id','title','description','severity']} defaults={{severity:'level_2'}} onAdd={input=>add('claim',input)}/><Table rows={data.claims} columns={['claim_code','lead_id','title','severity','status','opened_at']} empty="No claims."/></>}
    {tab === 'earnings' && <><div className="grid gap-3 md:grid-cols-3">{data.balances && Object.entries(data.balances).map(([k,v])=><div key={k} className="rounded-xl border bg-white p-4"><p className="text-xs font-bold uppercase text-slate-400">{k}</p><p className="text-xl font-black">${Number(v).toFixed(2)}</p></div>)}</div><Table rows={data.ledger} columns={['effective_at','description','entry_type','state','amount','currency']}/></>}
    {tab === 'performance' && <div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Measured performance</h2>{Object.entries(data.performance.metrics).map(([k,v])=><div key={k} className="mt-3 flex justify-between text-sm"><span>{k.replaceAll(/([A-Z])/g,' $1')}</span><b>{typeof v==='number' ? `${Math.round(v*100)}%` : String(v)}</b></div>)}</div><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Corrective actions</h2>{openActions.length ? openActions.map((x:any)=><div key={x.id} className="mt-3 rounded-xl bg-amber-50 p-3 text-sm"><b>{x.issue}</b><p>{x.required_action}</p></div>):<p className="mt-4 text-sm text-slate-400">No active corrective actions.</p>}</div></div>}
    {tab === 'audit' && <Table rows={data.audits} columns={['created_at','entity_type','action','actor_name','entity_id']}/>} </main>
}

function Table({rows,columns,empty='Nothing recorded.'}:{rows:any[];columns:string[];empty?:string}) { return <div className="overflow-x-auto rounded-2xl border bg-white">{rows.length?<table className="w-full text-left text-xs"><thead className="bg-slate-50"><tr>{columns.map(c=><th key={c} className="p-3 uppercase text-slate-400">{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i} className="border-t">{columns.map(c=><td key={c} className="p-3">{typeof r[c]==='boolean'?(r[c]?'Yes':'No'):r[c]==null?'—':String(r[c])}</td>)}</tr>)}</tbody></table>:<p className="p-8 text-center text-sm text-slate-400">{empty}</p>}</div> }
function QuickAdd({label,fields,defaults,onAdd}:{label:string;fields:string[];defaults:any;onAdd:(x:any)=>void}) { const [open,setOpen]=useState(false); const [form,setForm]=useState(defaults); return <div className="mb-3">{open?<form onSubmit={e=>{e.preventDefault();onAdd(form);setOpen(false)}} className="grid gap-2 rounded-xl border bg-white p-3 md:grid-cols-4">{fields.map(f=><input key={f} required value={form[f]||''} onChange={e=>setForm({...form,[f]:e.target.value})} placeholder={f.replaceAll('_',' ')} className="crm-input"/>)}<button className="rounded-lg bg-[#071421] px-4 py-2 text-xs font-bold text-white">Save</button></form>:<button onClick={()=>setOpen(true)} className="rounded-lg bg-[#071421] px-4 py-2 text-xs font-bold text-white">+ {label}</button>}</div> }
