import { requireSupabaseEnv } from '@/lib/server/runtime'
import type { PilotScenario, SimulationResult } from '@/lib/partner-simulations'

async function rest<T>(path: string, init?: RequestInit): Promise<T> { const {url,headers}=requireSupabaseEnv(); const r=await fetch(`${url}/rest/v1/${path}`,{...init,headers:{...headers,...(init?.headers||{})},cache:'no-store'}); if(!r.ok) throw new Error(`Partner pilot storage failed (${r.status}): ${await r.text()}`); if(r.status===204)return undefined as T; return r.json() as Promise<T> }
export async function saveSimulation(result: SimulationResult, runBy?: string) { return (await rest<any[]>('partner_simulation_runs',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({scenario:result.scenario,status:result.passed?'passed':'failed',events:result.events,assertions:result.assertions,run_by:runBy||null})}))[0] }
export async function listSimulations() { return rest<any[]>('partner_simulation_runs?select=*&order=created_at.desc&limit=100') }
function isUuid(value:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)}
export async function createOnboardingInvite(input:{subcontractorId?:string;phone?:string;email?:string;createdBy?:string}) { return (await rest<any[]>('partner_onboarding_invites',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({subcontractor_id:input.subcontractorId||null,phone:input.phone||null,email:input.email||null,created_by:input.createdBy||null,expires_at:new Date(Date.now()+14*86400000).toISOString()})}))[0] }
export async function listOnboardingInvites() { return rest<any[]>('partner_onboarding_invites?select=*&order=created_at.desc&limit=200') }
export async function getOnboardingInvite(token:string) { if(!isUuid(token))return null;return (await rest<any[]>(`partner_onboarding_invites?select=*&token=eq.${encodeURIComponent(token)}&limit=1`))[0]||null }
export async function updateOnboardingInvite(token:string,patch:any) { const rows=await rest<any[]>(`partner_onboarding_invites?token=eq.${encodeURIComponent(token)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({...patch,updated_at:new Date().toISOString()})}); return rows[0]||null }
export async function createJobEvent(input:{leadId:string;assignmentId?:string;subcontractorId?:string;eventType:string;tripNumber?:number;serviceDay?:number;actorName?:string;note?:string;facts?:any}) { return (await rest<any[]>('partner_job_events',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({lead_id:input.leadId,assignment_id:input.assignmentId||null,subcontractor_id:input.subcontractorId||null,event_type:input.eventType,trip_number:input.tripNumber||1,service_day:input.serviceDay||1,actor_name:input.actorName||null,note:input.note||null,facts:input.facts||{}})}))[0] }
export async function listJobEvents(leadId:string) { return rest<any[]>(`partner_job_events?select=*&lead_id=eq.${encodeURIComponent(leadId)}&order=occurred_at.asc`) }
export async function createChangeOrder(input:any) { return (await rest<any[]>('partner_change_orders',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(input)}))[0] }
export async function listChangeOrders(leadId?:string) { return rest<any[]>(`partner_change_orders?select=*${leadId?`&lead_id=eq.${encodeURIComponent(leadId)}`:''}&order=created_at.desc&limit=300`) }
export async function getChangeOrder(token:string) { if(!isUuid(token))return null;return (await rest<any[]>(`partner_change_orders?select=*&customer_token=eq.${encodeURIComponent(token)}&limit=1`))[0]||null }
export async function updateChangeOrder(id:string,patch:any) { return (await rest<any[]>(`partner_change_orders?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({...patch,updated_at:new Date().toISOString()})}))[0]||null }
export type { PilotScenario }
