"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const strict_1 = __importDefault(require("node:assert/strict"));
const stripe_accounts_1 = require("../../lib/server/stripe-accounts");
strict_1.default.equal((0, stripe_accounts_1.resolveStripeAccountKeyForLead)({ branch: 'ottawa' }), 'dexa');
strict_1.default.equal((0, stripe_accounts_1.resolveStripeAccountKeyForLead)({ branch: 'waterloo' }), 'saturn');
strict_1.default.equal((0, stripe_accounts_1.resolveStripeAccountKeyForLead)({ originCity: 'Kanata' }), 'dexa');
strict_1.default.equal((0, stripe_accounts_1.resolveStripeAccountKeyForLead)({ originCity: 'London' }), 'saturn');
strict_1.default.equal((0, stripe_accounts_1.resolveStripeAccountKeyForLead)({ originCity: 'Windsor', destCity: 'Ottawa' }), 'saturn');
strict_1.default.equal((0, stripe_accounts_1.resolveStripeAccountKeyForLead)({ originCity: 'Ottawa', destCity: 'Windsor' }), 'dexa');
strict_1.default.equal((0, stripe_accounts_1.resolveStripeAccountKeyForLead)({ destCity: 'Ottawa' }), 'dexa');
strict_1.default.equal((0, stripe_accounts_1.resolveStripeAccountKeyForLead)({ branch: 'windsor', originCity: 'Ottawa', destCity: 'Windsor' }), 'saturn');
strict_1.default.throws(() => (0, stripe_accounts_1.assertQuoteStripeAccount)({ stripeAccountKey: 'saturn' }, 'dexa'), /Payment account mismatch/);
strict_1.default.equal((0, stripe_accounts_1.reusableStripeCustomerId)({ stripeAccountKey: 'saturn', depositStripeCustomerId: 'cus_saturn' }, 'saturn'), 'cus_saturn');
strict_1.default.equal((0, stripe_accounts_1.reusableStripeCustomerId)({ depositStripeCustomerId: 'cus_legacy_saturn' }, 'dexa'), '');
strict_1.default.equal((0, stripe_accounts_1.webhookMetadataMatchesAccount)(undefined, 'saturn'), true);
strict_1.default.equal((0, stripe_accounts_1.webhookMetadataMatchesAccount)(undefined, 'dexa'), false);
strict_1.default.equal((0, stripe_accounts_1.webhookMetadataMatchesAccount)('dexa', 'saturn'), false);
strict_1.default.equal((0, stripe_accounts_1.webhookMetadataMatchesAccount)('dexa', 'dexa'), true);
