'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import type {summarizeCoverage} from '@/lib/partner-market-coverage'
type Report=ReturnType<typeof summarizeCoverage>
const label=(s:string)=>s.replaceAll('_',' ')
const n=(v:number|undefined)=>(v||0).toLocaleString()
export default function MarketCoveragePage(){
 const [data,setData]=useState<Report|null>(null),[error,setError]=useState(''),[city,setCity]=useState(''),[lane,setLane]=useState(''),[kind,setKind]=useState(''),[view,setView]=useState('people'),[loading,setLoading]=useState(true)
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetch('/api/marketing/market-coverage?'+new URLSearchParams({city,lane,kind}),{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setData(null)}}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[city,lane,kind])
 const tiles=data?[['Observed properties / units',n(data.totals.observed)],['Fresh active inventory',n(data.totals.active)],['Named representative',`${data.coverage.attributed_pct??'—'}%`],['Linked to our CRM',`${data.coverage.linked_pct??'—'}%`],['Recorded outreach coverage',`${data.coverage.reached_pct??'—'}%`],['Inbound history coverage',`${data.coverage.inbound_pct??'—'}%`]]:[]
 return <main className="mx-auto max-w-7xl p-4 sm:p-6">
  <Link href="/marketing/listing-activity" className="text-sm underline">← Partner Event Desk</Link>
  <h1 className="mt-4 text-2xl font-semibold">Market coverage</h1>
  <p className="mt-2 text-sm text-slate-600">See who handles the inventory we observe, which brokerages are active, and where our relationships reach.</p>
  <p className="mt-2 text-xs text-slate-500">Coverage is measured against our stored inventory, not the entire market or moving-job market share. A reply can be an opt-out or an automatic response; it does not establish a positive relationship.</p>
  <div className="my-5 flex flex-wrap gap-3">{[['City',city,setCity,data?.facets.cities],['Market',lane,setLane,data?.facets.lanes],['Property type',kind,setKind,data?.facets.kinds]].map(([title,value,set,options])=><select key={String(title)} aria-label={String(title)} className="rounded-lg border p-2" value={value as string} onChange={e=>(set as (v:string)=>void)(e.target.value)}><option value="">All {String(title).toLowerCase()}</option>{(options as string[]||[]).map(x=><option key={x} value={x}>{label(x)}</option>)}</select>)}</div>
  {loading?<p>Loading market coverage…</p>:error?<p role="alert" className="text-red-700">{error}</p>:data&&<>
   <p className="mb-4 text-xs text-slate-500">Snapshot {new Date(data.generated_at).toLocaleString()} · {data.scope}</p>
   <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{tiles.map(([title,value])=><div key={title} className="rounded-xl border bg-white p-4"><p className="text-xs text-slate-600">{title}</p><strong className="mt-2 block text-2xl">{value}</strong></div>)}</div>
   <p className="my-4 text-sm text-slate-600">{n(data.totals.stale)} stale / undated · {n(data.totals.observed-data.totals.attributed)} without a named representative · {n(data.totals.newly_observed)} first observed in {data.recent_days} days · {n(data.totals.postcard_excluded)} with postcard exclusions retained</p>
   <p className="text-xs text-slate-500">Fresh active = stored active and observed within {data.freshness_days} days. First observed is not a confirmed listing date. Removed listings are not counted as confirmed sales. House / condo classifications remain unknown when source evidence is missing.</p>
   <div className="my-5 flex gap-3"><button className={`rounded border px-4 py-2 ${view==='people'?'bg-slate-900 text-white':''}`} onClick={()=>setView('people')}>Representatives</button><button className={`rounded border px-4 py-2 ${view==='brokerages'?'bg-slate-900 text-white':''}`} onClick={()=>setView('brokerages')}>Brokerages</button></div>
   {view==='people'?<><p className="mb-3 text-sm">{n(data.identity_counts.linked)} linked CRM identities · {n(data.identity_counts.unverified)} unverified identity groups. Ranked by fresh active inventory; showing up to {data.display_limit}.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Representative / role','Brokerage','Active','Observed','Outreach / inbound','Evidence'].map(h=><th key={h} className="border-b p-3">{h}</th>)}</tr></thead><tbody>{data.people.map(p=><tr key={p.key}><td className="border-b p-3">{p.contact_id?<Link className="underline" href={`/marketing/partners?tab=phone&contact=${p.contact_id}`}>{p.name}</Link>:p.name}<p className="text-xs text-slate-500">{label(p.role)} · {p.contact_id?'CRM linked':'Identity needs verification'}</p></td><td className="border-b p-3">{p.brokerage||'Unknown'}</td><td className="border-b p-3">{n(p.counts.active)}</td><td className="border-b p-3">{n(p.counts.observed)}</td><td className="border-b p-3">{p.counts.reached?'Recorded':'None recorded'} / {p.counts.replied?'Recorded':'None recorded'}{p.counts.suppressed>0&&<p className="text-xs text-red-700">Do not contact</p>}</td><td className="border-b p-3">{p.samples.filter(s=>/^https?:\/\//i.test(s.url)).map((s,i)=><a key={i} className="block text-xs underline" href={s.url} target="_blank" rel="noreferrer">{s.address}</a>)}</td></tr>)}</tbody></table></div></>:<><p className="mb-3 text-sm">{n(data.total_brokerages)} reported brokerages. Branch names remain separate. Co-listed properties may appear under multiple brokerages, so shares need not sum to 100%.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Brokerage','Active','Observed','Observed share','CRM-linked properties','Outreach coverage'].map(h=><th key={h} className="border-b p-3">{h}</th>)}</tr></thead><tbody>{data.brokerages.map(b=><tr key={b.key}><td className="border-b p-3">{b.name}</td><td className="border-b p-3">{n(b.counts.active)}</td><td className="border-b p-3">{n(b.counts.observed)}</td><td className="border-b p-3">{b.observed_share_pct??'—'}%</td><td className="border-b p-3">{n(b.counts.linked)}</td><td className="border-b p-3">{n(b.counts.reached)} / {n(b.counts.observed)}</td></tr>)}</tbody></table></div></>}
  </>}
 </main>
}
