'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'

type Report = { id: string; leadId: string; subcontractorId?: string; offerId?: string; reportType: string; severity: string; status: string; summary: string; details?: string; requestedExtraHours?: number; requestedAdjustment?: number; reportedBy?: string; resolutionNote?: string; createdAt: string }
type Message = { id: string; subcontractorId?: string; offerId?: string; direction: string; channel: string; body: string; senderName?: string; urgent: boolean; createdAt: string }
type Job = { id: string; name: string; moveDate?: string; branch?: string }

export default function PartnerOperationsPage() {
  const [reports, setReports] = useState<Report[]>([]); const [jobs, setJobs] = useState<Job[]>([])
  const [selectedLeadId, setSelectedLeadId] = useState(''); const [messages, setMessages] = useState<Message[]>([])
  const [reply, setReply] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  async function loadQueue() { const response = await fetch('/api/sales/partner-operations', { cache: 'no-store' }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setReports(body.reports); setJobs(body.jobs) }
  async function loadThread(leadId: string) { setSelectedLeadId(leadId); const response = await fetch(`/api/sales/partner-operations?leadId=${encodeURIComponent(leadId)}`, { cache: 'no-store' }); const body = await response.json(); if (response.ok) setMessages(body.messages || []) }
  useEffect(() => { loadQueue().catch(error => setMessage(error.message)) }, [])
  const openReports = useMemo(() => reports.filter(item => !['resolved','closed','declined'].includes(item.status)).sort((a, b) => ({ critical: 3, urgent: 2, routine: 1 }[b.severity] || 0) - ({ critical: 3, urgent: 2, routine: 1 }[a.severity] || 0)), [reports])
  const activeReport = openReports.find(item => item.leadId === selectedLeadId) || reports.find(item => item.leadId === selectedLeadId)
  async function updateReport(report: Report, status: string) { setBusy(true); const response = await fetch('/api/sales/partner-operations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'update_report', leadId: report.leadId, reportId: report.id, status }) }); const body = await response.json(); setMessage(response.ok ? `Report marked ${status}.` : body.error); setBusy(false); await loadQueue() }
  async function sendReply() { if (!activeReport?.subcontractorId || !reply.trim()) return; setBusy(true); const response = await fetch('/api/sales/partner-operations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'reply', leadId: activeReport.leadId, subcontractorId: activeReport.subcontractorId, offerId: activeReport.offerId, message: reply, urgent: activeReport.severity !== 'routine' }) }); const body = await response.json(); setMessage(response.ok ? 'Reply sent from the Operations number.' : body.error); if (response.ok) { setReply(''); await loadThread(activeReport.leadId) } setBusy(false) }
  return <main className="crm-shell space-y-6"><header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#C99700]">Partner network</p><h1 className="font-display text-2xl font-bold text-[#071421]">Operations Communications</h1><p className="mt-1 text-sm text-slate-500">Police-style field reporting: factual, timestamped, job-linked, and permanently auditable.</p></div><div className="flex gap-2"><Link href="/sales/operations" className="rounded-lg border bg-white px-4 py-2 text-sm font-bold">Operations board</Link><Link href="/sales/contractors" className="rounded-lg bg-[#071421] px-4 py-2 text-sm font-bold text-white">Partner 360</Link></div></header>
    {message && <div className="rounded-xl border border-sky-200 bg-sky-50 p-3 text-sm text-sky-800">{message}</div>}
    <div className="grid gap-5 lg:grid-cols-[380px_1fr]"><section className="space-y-3"><div className="flex items-center justify-between"><h2 className="font-bold text-[#071421]">Needs attention</h2><span className="rounded-full bg-rose-100 px-2 py-1 text-xs font-bold text-rose-700">{openReports.length} open</span></div>{openReports.length ? openReports.map(report => <button key={report.id} onClick={() => loadThread(report.leadId)} className={`w-full rounded-xl border p-4 text-left ${selectedLeadId === report.leadId ? 'border-[#C99700] bg-amber-50' : report.severity === 'critical' ? 'border-rose-300 bg-rose-50' : 'bg-white'}`}><div className="flex justify-between gap-2"><span className="text-[10px] font-bold uppercase tracking-wide text-rose-700">{report.severity} · {report.reportType.replaceAll('_', ' ')}</span><span className="text-[10px] text-slate-400">{new Date(report.createdAt).toLocaleString()}</span></div><p className="mt-2 text-sm font-bold text-[#071421]">{report.summary}</p><p className="mt-1 text-xs text-slate-500">Job {report.leadId} · {report.reportedBy || 'Partner'}</p></button>) : <div className="rounded-xl border border-dashed bg-white p-8 text-center text-sm text-slate-400">No open partner exceptions.</div>}</section>
      <section className="rounded-2xl border bg-white p-5">{selectedLeadId ? <><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold text-[#071421]">Job {selectedLeadId}</h2><p className="text-xs text-slate-500">{jobs.find(item => item.id === selectedLeadId)?.name} · {jobs.find(item => item.id === selectedLeadId)?.moveDate || 'date TBD'}</p></div><Link href={`/sales/leads/${selectedLeadId}`} className="text-xs font-bold underline">Open full job</Link></div>{activeReport && <div className="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-4"><div className="text-xs font-bold uppercase text-rose-700">Field report · {activeReport.status}</div><p className="mt-2 font-bold">{activeReport.summary}</p>{activeReport.details && <p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{activeReport.details}</p>}<div className="mt-3 flex flex-wrap gap-2">{activeReport.status === 'reported' && <button disabled={busy} onClick={() => updateReport(activeReport, 'acknowledged')} className="rounded-lg bg-amber-500 px-3 py-2 text-xs font-bold text-white">Acknowledge</button>}<button disabled={busy} onClick={() => updateReport(activeReport, 'investigating')} className="rounded-lg bg-[#071421] px-3 py-2 text-xs font-bold text-white">Investigating</button><button disabled={busy} onClick={() => updateReport(activeReport, 'approved')} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Approve request</button><button disabled={busy} onClick={() => updateReport(activeReport, 'resolved')} className="rounded-lg border bg-white px-3 py-2 text-xs font-bold">Resolve</button></div></div>}
        <div className="mt-4 max-h-[420px] space-y-2 overflow-y-auto rounded-xl bg-slate-50 p-3">{messages.map(item => <div key={item.id} className={`rounded-xl p-3 text-sm ${item.direction === 'operations_to_partner' ? 'ml-8 bg-[#071421] text-white' : 'mr-8 border bg-white'}`}><div className="text-[10px] font-bold uppercase opacity-60">{item.senderName || item.channel} · {new Date(item.createdAt).toLocaleString()}</div><p className="mt-1 whitespace-pre-wrap">{item.body}</p></div>)}</div><div className="mt-3 flex gap-2"><textarea value={reply} onChange={event => setReply(event.target.value)} placeholder="Reply to partner. This sends from the dedicated Operations SMS number and remains attached to the job." className="min-h-20 min-w-0 flex-1 rounded-xl border p-3 text-sm"/><button disabled={busy || !reply.trim()} onClick={sendReply} className="rounded-xl bg-[#071421] px-5 text-sm font-bold text-white disabled:opacity-40">Send SMS</button></div></> : <div className="flex min-h-[420px] items-center justify-center text-sm text-slate-400">Choose an exception to open its complete job communication history.</div>}</section></div>
  </main>
}
